<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container658mfRT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container658mfRT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container658mfRT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container658mfRT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container658mfRT\App_KernelDevDebugContainer([
    'container.build_hash' => '658mfRT',
    'container.build_id' => '6103f7c2',
    'container.build_time' => 1651574598,
], __DIR__.\DIRECTORY_SEPARATOR.'Container658mfRT');
