<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUJYJt9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUJYJt9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEUJYJt9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEUJYJt9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEUJYJt9\App_KernelDevDebugContainer([
    'container.build_hash' => 'EUJYJt9',
    'container.build_id' => '8910a0df',
    'container.build_time' => 1651584149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUJYJt9');
