<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWJMaRux\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWJMaRux/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWJMaRux.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWJMaRux\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWJMaRux\App_KernelDevDebugContainer([
    'container.build_hash' => 'WJMaRux',
    'container.build_id' => '0a173766',
    'container.build_time' => 1651576769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWJMaRux');
